[build]
  functions = "netlify/functions"
  publish   = "."

[dev]
  port        = 8888
  targetPort  = 8888
  autoLaunch  = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "DENY"
    X-Content-Type-Options = "nosniff"
